name = "SyncBarriersBenchmarks"
uuid = "72ebdf5a-2200-4ea8-af32-0d16f67d4260"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SyncBarriers = "3986aa12-c984-439b-887a-f8545bea0e93"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
julia = "1"
